// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXLMgks-Di8E8L4U8jYv__fHEWyRcmQ4k',
    appId: '1:859816856959:web:14158c6007078376329e4a',
    messagingSenderId: '859816856959',
    projectId: 'cuentaspersonales-36328',
    authDomain: 'cuentaspersonales-36328.firebaseapp.com',
    storageBucket: 'cuentaspersonales-36328.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBco4RRfqs-LnCb2tztf5a9j7jGv1K5xw8',
    appId: '1:859816856959:android:825483d85d9c8ba1329e4a',
    messagingSenderId: '859816856959',
    projectId: 'cuentaspersonales-36328',
    storageBucket: 'cuentaspersonales-36328.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaTY4t8eLj1oMdXZbL8RGbP8Oz29PDmvo',
    appId: '1:859816856959:ios:508c8f09dde43f7e329e4a',
    messagingSenderId: '859816856959',
    projectId: 'cuentaspersonales-36328',
    storageBucket: 'cuentaspersonales-36328.firebasestorage.app',
    iosBundleId: 'com.example.cuentasPersonales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaTY4t8eLj1oMdXZbL8RGbP8Oz29PDmvo',
    appId: '1:859816856959:ios:a47d4f78d736986d329e4a',
    messagingSenderId: '859816856959',
    projectId: 'cuentaspersonales-36328',
    storageBucket: 'cuentaspersonales-36328.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXLMgks-Di8E8L4U8jYv__fHEWyRcmQ4k',
    appId: '1:859816856959:web:8abc986221fca5b6329e4a',
    messagingSenderId: '859816856959',
    projectId: 'cuentaspersonales-36328',
    authDomain: 'cuentaspersonales-36328.firebaseapp.com',
    storageBucket: 'cuentaspersonales-36328.firebasestorage.app',
  );
}
